name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.0.0-nullsafety.3
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.1.6
  geolocator: ^8.2.1
  provider: ^6.0.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^1.3.0
  tuple: ^2.0.0
  http: ^0.13.4
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
