name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.2.0
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.2.4
  geolocator: ^12.0.0
  provider: ^6.0.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^4.0.3
  tuple: ^2.0.2
  http: ^0.13.6
  # location: ^5.0.0-dev.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
