name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.0.0-nullsafety.3
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.0.8
  geolocator: ^7.6.0
  provider: ^6.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^1.1.1
  tuple: ^2.0.0
  http: ^0.13.3
  location: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
